/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DriverCard {
        "age": string;
        "global": string;
        "name": string;
        "picture": string;
        "team": string;
    }
}
declare global {
    interface HTMLDriverCardElement extends Components.DriverCard, HTMLStencilElement {
    }
    var HTMLDriverCardElement: {
        prototype: HTMLDriverCardElement;
        new (): HTMLDriverCardElement;
    };
    interface HTMLElementTagNameMap {
        "driver-card": HTMLDriverCardElement;
    }
}
declare namespace LocalJSX {
    interface DriverCard {
        "age"?: string;
        "global"?: string;
        "name"?: string;
        "picture"?: string;
        "team"?: string;
    }
    interface IntrinsicElements {
        "driver-card": DriverCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "driver-card": LocalJSX.DriverCard & JSXBase.HTMLAttributes<HTMLDriverCardElement>;
        }
    }
}
