/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonRaces {
    }
}
declare global {
    interface HTMLButtonRacesElement extends Components.ButtonRaces, HTMLStencilElement {
    }
    var HTMLButtonRacesElement: {
        prototype: HTMLButtonRacesElement;
        new (): HTMLButtonRacesElement;
    };
    interface HTMLElementTagNameMap {
        "button-races": HTMLButtonRacesElement;
    }
}
declare namespace LocalJSX {
    interface ButtonRaces {
    }
    interface IntrinsicElements {
        "button-races": ButtonRaces;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-races": LocalJSX.ButtonRaces & JSXBase.HTMLAttributes<HTMLButtonRacesElement>;
        }
    }
}
